### PR TITLE
more testing cleanup

### PR DESCRIPTION
**Pull request by dagar**
@LorenzMeier the overall goal is to have a single tests command that runs everywhere. I wanted to use a nice testing framework like gtest, doctest, check, etc, but they're actually quite difficult to get working on Nuttx. After wasting more time than I'd care to admit I decided PX4 unit_test and all of its boilerplate is good enough.

- run `tests all` in posix_sitl on travis-ci
- start moving unittests/ -> systemcmds/tests/ (we could probably entirely kill unittests/)
- `tests all` now runs commander_tests, mavlink_tests, controllib_test, uorb_test
- added `make quick_check` for developers to build common targets (pixhawk, pixracer, test, format)
- start using unit_test for some tests
- TODO: mavlink tests is broken everywhere

### CODE REVIEW

**Comment by dagar** [comment]
I should remove the posix_sitl_test config. It's now identical to posix_sitl_default, but with a different init script.

**Comment by LorenzMeier** [comment]
@dagar Thanks! Just not too quick: I want a standardised test framework for library calls and parsers (GTest) and I do *not* want to run SITL just to execute those. Consolidating the in-app usage is fine, but not at the expense of throwing out GTest and lightweight testing on the host.

**Comment by dagar** [comment]
Is it the lightweight testing on the host, or gtest you don't want to get rid of?

This is a stripped down SITL init (https://github.com/dagar/Firmware/blob/testing/posix-configs/SITL/init/rcS_tests) with no simulator or other apps. It's nearly as lightweight as external unit tests. It launches and starts running the first test almost instantly.

Dropping gtest is unfortunate, but it was only done because I think it's incredibly important to run testing on the actual hardware. This way you have most of the same core testing that you can quickly run on the host as part of development. We have the same basic gtest functionality with unit_test, it's just not as nice.

I started down this path because the standalone unit test was slowly turning into a crappy parallel SITL with many subtle differences. See https://github.com/PX4/Firmware/blob/master/unittests/CMakeLists.txt#L100
Adding new tests was a pain because you had to figure out how to build the part you wanted to test standalone. If you absolutely wanted to keep gtest it would still be better to build and run it as an app in SITL. I also explored replacing mainapp with gtest_main.

If there's testing that doesn't make sense to run from within an app, or can't be then we can still do it externally.

**Comment by dagar** [comment]
@LorenzMeier can we merge this or would you like to discuss which tests stay as standalone gtests?
To try this you can do `make tests` (also runs on travis-ci) or flash the px4fmu-v2_test target.

**Comment by LorenzMeier** [comment]
@dagar Can you try to rebase against master? I can't seem to get this to compile on Mac OS.

**Comment by dagar** [comment]
Rebased.
It's building on travis-ci OSX (obviously), but I haven't tried actually running the tests there. 
The existing unittests/ were disabled on OSX a long time ago for various reasons, so I wouldn't be surprised if there are some issues.

Try `make tests`

**Comment by LorenzMeier** [comment]
The first build goes through, the second which is triggered by make tests fails - is this within DriverFramework?

```
s -D__CUSTOM_FILE_IO__ -D__PX4_UNIT_TESTS -g -Wall -Werror -g3 -fsanitize=address -fno-omit-frame-pointer -Wno-sign-compare -Wno-unused-but-set-variable -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -MMD -MT CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/i2c_posix.cpp.o -MF CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/i2c_posix.cpp.o.d -o CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/i2c_posix.cpp.o -c /Users/lorenzmeier/src/Firmware/src/drivers/device/i2c_posix.cpp
clang: error: unsupported argument 'address' to option 'fsanitize='
[10/38] Building CXX object CMakeFiles/px4_platform.d...renzmeier/src/Firmware/src/drivers/device/vfile.cpp.
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DERROR=-1 -DOK=0 -D_UNIT_TEST="" -D__EXPORT="" -D__PX4_DARWIN -D__PX4_POSIX -D__PX4_TESTS -Dmain_t=int -Dnoreturn_function="" -I/Users/lorenzmeier/src/Firmware/unittests/googletest/include -I/Users/lorenzmeier/src/Firmware/unittests -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules/param -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules/uORB -I/Users/lorenzmeier/src/Firmware/unittests/../src -I/Users/lorenzmeier/src/Firmware/unittests/../src/drivers -I/Users/lorenzmeier/src/Firmware/unittests/../src/drivers/device -I/Users/lorenzmeier/src/Firmware/unittests/../src/lib -I/Users/lorenzmeier/src/Firmware/unittests/../src/lib/DriverFramework/framework/include -I/Users/lorenzmeier/src/Firmware/unittests/../src/modules -I/Users/lorenzmeier/src/Firmware/unittests/../src/modules/uORB -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms/posix/include -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms/posix/px4_layer -std=c++11 -fno-exceptions -fno-rtti -fno-threadsafe-statics -D__CUSTOM_FILE_IO__ -D__PX4_UNIT_TESTS -g -Wall -Werror -g3 -fsanitize=address -fno-omit-frame-pointer -Wno-sign-compare -Wno-unused-but-set-variable -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -MMD -MT CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vfile.cpp.o -MF CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vfile.cpp.o.d -o CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vfile.cpp.o -c /Users/lorenzmeier/src/Firmware/src/drivers/device/vfile.cpp
clang: error: unsupported argument 'address' to option 'fsanitize='
[10/38] Building CXX object CMakeFiles/px4_platform.d...eier/src/Firmware/src/drivers/device/vdev_posix.cpp.
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DERROR=-1 -DOK=0 -D_UNIT_TEST="" -D__EXPORT="" -D__PX4_DARWIN -D__PX4_POSIX -D__PX4_TESTS -Dmain_t=int -Dnoreturn_function="" -I/Users/lorenzmeier/src/Firmware/unittests/googletest/include -I/Users/lorenzmeier/src/Firmware/unittests -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules/param -I/Users/lorenzmeier/src/Firmware/unittests/../src/../build_posix_sitl_default/src/modules/uORB -I/Users/lorenzmeier/src/Firmware/unittests/../src -I/Users/lorenzmeier/src/Firmware/unittests/../src/drivers -I/Users/lorenzmeier/src/Firmware/unittests/../src/drivers/device -I/Users/lorenzmeier/src/Firmware/unittests/../src/lib -I/Users/lorenzmeier/src/Firmware/unittests/../src/lib/DriverFramework/framework/include -I/Users/lorenzmeier/src/Firmware/unittests/../src/modules -I/Users/lorenzmeier/src/Firmware/unittests/../src/modules/uORB -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms/posix/include -I/Users/lorenzmeier/src/Firmware/unittests/../src/platforms/posix/px4_layer -std=c++11 -fno-exceptions -fno-rtti -fno-threadsafe-statics -D__CUSTOM_FILE_IO__ -D__PX4_UNIT_TESTS -g -Wall -Werror -g3 -fsanitize=address -fno-omit-frame-pointer -Wno-sign-compare -Wno-unused-but-set-variable -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -MMD -MT CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vdev_posix.cpp.o -MF CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vdev_posix.cpp.o.d -o CMakeFiles/px4_platform.dir/Users/lorenzmeier/src/Firmware/src/drivers/device/vdev_posix.cpp.o -c /Users/lorenzmeier/src/Firmware/src/drivers/device/vdev_posix.cpp
clang: error: unsupported argument 'address' to option 'fsanitize='
[10/38] Building C object CMakeFiles/px4_platform.dir...rc/Firmware/src/platforms/posix/px4_layer/drv_hrt.c.
ninja: build stopped: subcommand failed.
make: *** [unittest] Error 1
```

**Comment by LorenzMeier** [comment]
```clang --version
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
```

**Comment by LorenzMeier** [comment]
Maybe its my prehistoric Xcode. Let me check.

**Comment by dagar** [comment]
`make tests` is both the unittests/ and posix_sitl_default with the init script that runs the testing.
Address sanitizer is enabled in unittests/CMakeLists.txt. 
As a quick test you can try removing unittest here - https://github.com/dagar/Firmware/blob/testing/Makefile#L290
That would show you how the rest of it is doing.

**Comment by dagar** [comment]
I split `make tests`. You can individually try `make run_tests_posix` and `make unittest` now.

**Comment by LorenzMeier** [comment]
Current mac OS build error:

```
In file included from ../src/systemcmds/tests/tests_main.c:48:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdlib.h:267:132: fatal error: expected a version of the form 'major[.minor[.subminor]]'
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
                                                                                                                                       ^
1 error generated.
```

**Comment by dagar** [comment]
Which xcode should the build system be using? Which versions do you want to "support"?

**Comment by LorenzMeier** [comment]
The most recent one. So we need to fix this build error

**Comment by dagar** [comment]
@LorenzMeier OSX build issue resolved.

**Comment by LorenzMeier** [comment]
@dagar almost:
```
$ make unittest
PX4 CONFIG: posix_sitl_default
ninja: no work to do.
-- Found PythonInterp: /usr/local/bin/python (found version "1.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lorenzmeier/src/Firmware/unittests
ninja: error: loading 'build.ninja': No such file or directory
make: *** [unittest] Error 1
```

**Comment by dagar** [comment]
I was just talking about posix_sitl_default (now with tests included), but I might as well get the entire thing working on OSX.

**Comment by dagar** [comment]
`make unittest` OSX issues.

    /Users/travis/build/PX4/Firmware/unittests/../src/../build_posix_sitl_default/libmsg_gen.a googletest/libgtest_main.a -lpthread libpx4_platform.a googletest/libgtest.a && :
    Undefined symbols for architecture x86_64:
      "__hrt_work_lock", referenced from:
      _hrt_work_lock in libpx4_platform.a(hrt_work_cancel.c.o)
      _hrt_work_unlock in libpx4_platform.a(hrt_work_cancel.c.o)
      _hrt_work_lock in libpx4_platform.a(hrt_queue.c.o)
      _hrt_work_unlock in libpx4_platform.a(hrt_queue.c.o)
      "_g_hrt_work", referenced from:
      _hrt_work_cancel in libpx4_platform.a(hrt_work_cancel.c.o)
      _hrt_work_queue in libpx4_platform.a(hrt_queue.c.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

**Comment by LorenzMeier** [comment]
Looks like an incorrect ifdef symptom of something like that.

**Comment by dagar** [comment]
hmm, I can't figure out what's missing on OSX to get `make unittest` working, but the test suite within SITL works (`make run_tests_posix`).

**Comment by dagar** [comment]
After rebasing on master today there's a consistent uorb test failure only on OSX.

https://travis-ci.org/PX4/Firmware/jobs/140605692#L457

    --------------------------------------------------------------------------------
      [uorb] 		STARTING TEST
    RB note: ---------------- LATENCY TEST ------------------
    uORB note: PASS multi-topic test
    uORB note: try multi-topic support subscribing before publishing
    uORB note: advertised
    uORB note: published
    uORB note: PASS multi-topic reversed
    uORB note: Testing unadvertise
    uORB note: PASS unadvertise
    uORB note: Testing multi-topic 2 test (queue simulation)
    uORB FAIL: Timestamp not increasing! (4844094 >= 4844069)
    [uORBTest] 		FAIL
      [uorb] 		FAIL
    WARN  [uorb_tests] mean:  27.0500 us
    --------------------------------------------------------------------------------

**Comment by dagar** [comment]
I don't have a Mac so there's not much I can do to fix OSX only test failures. I've disabled running the tests in the OSX build for now.

@LorenzMeier can we merge this and then if someone with a Mac can fix `make tests` they can be enabled in the builds and kept working?

**Comment by LorenzMeier** [comment]
Squash-merged onto master, thanks!

**Comment by dagar** [comment]
A couple things broke between the last time this PR built and now. Fixing
here - https://github.com/PX4/Firmware/pull/5163
