### ISSUE TITLE
native build error

### ISSUE THREAD

**Issue by kauHyunju** [PX4/Firmware#5334]
Hello.
I'm working in Ubuntu 12.04. 
Specifically,
Linux ubuntu 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:39:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I got a make error. (make posix_rpi_native)
Below is the error message.

Firmware/src/drivers/navio_sysfs_pwm_out/navio_sysfs_pwm_out.cpp: In function ‘int navio_sysfs_pwm_out::initialize_mixer(const char*)’:
Firmware/src/drivers/navio_sysfs_pwm_out/navio_sysfs_pwm_out.cpp:138:98: error: no matching function for call to ‘MultirotorMixer::from_text(int (&)(uintptr_t, uint8_t, uint8_t, float&), uintptr_t, char [2048], size_t&)’
    _mixer = MultirotorMixer::from_text(mixer_control_callback, (uintptr_t)&_controls, buf, buflen);

How can I fix it?

**Comment by bkueng** [comment]
fixed in master
