### ISSUE TITLE
Compile error with -Weffc++

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#7040]
On current master I get the following compile error:
```
../src/lib/matrix/matrix/Vector.hpp:20:7: error: base class 'class matrix::Matrix<float, 3u, 1u>' has a non-virtual destructor [-Werror=effc++]
 class Vector : public Matrix<Type, M, 1>
```

This is a false alarm and got introduced with https://github.com/PX4/Matrix/commit/66e1b406b8a68422135c365d42b987a64c9ddf8d

In general I agree with Scott Meyer's recommondations, but I'm starting to doubt the usefulness of the GCC flag. Also since we have clang-tidy that does similar things. @dagar what do you think?

**Comment by dagar** [comment]
Yes, I agree. Are you hitting this with a different version of GCC locally or a different set of flags?

**Comment by bkueng** [comment]
I currently use GCC 4.8.4, without any other local changes.

**Comment by ndepal** [comment]
Just ran into this too on OSX, GCC 4.8.4. Is there a quick fix? Where do I disable that flag?

**Comment by dagar** [comment]
Alright let's get rid of it. I need to see why the build system didn't catch this.

https://github.com/PX4/Firmware/pull/7044
