### ISSUE TITLE
PX4 SITL build failure with i2c-dev package installed

### ISSUE THREAD

**Issue by sfalexrog** [PX4/Firmware#11137]
**Describe the bug**
PX4 SITL fails to build on Ubuntu 16.04 (and possibly other Debian-based systems) with [libi2c-dev](https://packages.ubuntu.com/xenial/libi2c-dev) package installed.

```libi2c-dev``` package replaces ```/usr/include/linux/i2c-dev.h``` header with its own version that has its own definition of ```struct i2c_msg```. This results in a compilation failure each time both ```<linux/i2c.h>``` and ```<linux/i2c-dev.h``` are included.

**To Reproduce**

1. Prepare a PX4 development environment based on Ubuntu 16.04
1. Install ```libi2c-dev``` package
1. Run ```make px4_sitl jmavsim```
1. Observer compilation error

**Expected behavior**
Clean build and a running jmavsim with PX4 SITL

**Log Files and Screenshots**
Build log snippet:

    ninja: Entering directory `/home/sf/devel/px4/Firmware_master/build/px4_sitl_default'
    [13/698] Building CXX object src/lib/D...f_driver_framework.dir/I2CDevObj.cpp.o
    FAILED: /usr/bin/c++ -DCONFIG_ARCH_BOARD_PX4_SITL -DENABLE_LOCKSTEP_SCHEDULER -D__CUSTOM_FILE_IO__ -D__DF_LINUX -D__PX4_LINUX -D__PX4_POSIX -D__STDC_FORMAT_MACROS -Dnoreturn_function="__attribute__((noreturn))" -I../../boards/px4/sitl/src -I. -Isrc -Isrc/lib -Isrc/modules -I../../src -I../../src/include -I../../src/lib -I../../src/lib/DriverFramework/framework/include -I../../src/lib/matrix -I../../src/modules -I../../src/platforms -I../../platforms/posix/include -O2 -g -DNDEBUG -fPIC -g -fdata-sections -ffunction-sections -fomit-frame-pointer -funsafe-math-optimizations -fno-strict-aliasing -fno-math-errno -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -std=gnu++11 -MMD -MT src/lib/DriverFramework/framework/src/CMakeFiles/df_driver_framework.dir/I2CDevObj.cpp.o -MF src/lib/DriverFramework/framework/src/CMakeFiles/df_driver_framework.dir/I2CDevObj.cpp.o.d -o src/lib/DriverFramework/framework/src/CMakeFiles/df_driver_framework.dir/I2CDevObj.cpp.o -c ../../src/lib/DriverFramework/framework/src/I2CDevObj.cpp
    In file included from ../../src/lib/DriverFramework/framework/src/I2CDevObj.cpp:50:0:
    /usr/include/linux/i2c.h:68:8: error: redefinition of ‘struct i2c_msg’
    struct i2c_msg {
    ^
    compilation terminated due to -Wfatal-errors.
    **Additional context**
Definition of ```struct i2c_msg``` differs slightly in ```<linux/i2c.h>``` as provided by the Linux kernel and ```<linux/i2c-dev.h>``` as provided by ```libi2c-dev```; for example, the ```buf``` field is defined as ```__u8``` in my ```i2c.h```, but is a ```char *``` in ```i2c-dev.h```.

Affected files (where both ```i2c.h``` and ```i2c-dev.h``` are included) are both in the main project and in the [DriverFramework](https://github.com/PX4/DriverFramework) submodule.

The issue does not affect building PX4 firmwares for actual hardware.
