### ISSUE TITLE
Can't compile for gazebo on Mac

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4169]
I tried to follow the steps in the devguide to get the gazebo sim working on Mac OS X10.11.4.

Unfortunately `make posiz gazebo` fails to compile as follows:

```
Scanning dependencies of target rotors_gazebo_motor_model
In file included from /Users/julianoes/src/Firmware/Tools/sitl_gazebo/src/gazebo_opticalFlow_plugin.cpp:24:
In file included from /Users/julianoes/src/Firmware/Tools/sitl_gazebo/include/gazebo_opticalFlow_plugin.h:26:
In file included from /usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5/gazebo/rendering/Camera.hh:44:
In file included from /usr/local/Cellar/gazebo6/6.5.1/include/gazebo-6.5/gazebo/rendering/ogre_gazebo.h:61:
/usr/local/include/OGRE/Terrain/OgreTerrainPaging.h:33:10: fatal error: 
      'OgrePagedWorldSection.h' file not found
#include "OgrePagedWorldSection.h"
```

**Comment by LorenzMeier** [comment]
Will look into this.

**Comment by nicolaerosia** [comment]
Can you try https://github.com/PX4/sitl_gazebo/pull/13 ?

**Comment by LorenzMeier** [comment]
Fixed, thanks!
