### PR TITLE
Fix compilation errors with GCC 7

### PR DESCRIPTION
**Pull request by jlecoeur**
With newer versions of GCC, new warnings are emitted and prevent building the posix target on master.

You can find the compiler errors [here](https://gist.github.com/jlecoeur/2aef4f397b5e564e231929195db84742) (I use GCC 7.1.1 on archlinux).

I also had to fix an error in the ecl submodule. I temporarily changed the submodule URL for the tests, but this has to be reverted.

### CODE REVIEW

File: src/systemcmds/tests/test_matrix.cpp [hunk 1]
```diff
@@ -625,7 +625,7 @@ bool MatrixTest::vector2Tests()
 	ut_test(fabs(c(1) - 0) < 1e-5);
 
 	Matrix<float, 2, 1> d(a);
-	ut_test(fabs(d(0, 0) - 1) < 1e-5);
+	ut_test(fabs(d(0, 0) - 1.0f) < 1e-5);
```
Comment (jlecoeur) [inline src/systemcmds/tests/test_matrix.cpp]: I cannot explain why I had to make this change, and why only here.
The compiler was not helpful:
```
/run/media/julien/Data/Documents/PX4/Firmware/src/systemcmds/tests/test_matrix.cpp: In member function ‘bool MatrixTest::vector2Tests()’:
/run/media/julien/Data/Documents/PX4/Firmware/src/systemcmds/tests/test_matrix.cpp:640:1: internal compiler error: in trunc_int_for_mode, at explow.c:55
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
```

File: src/modules/mavlink/mavlink_ftp.cpp [hunk 2]
```diff
@@ -361,11 +361,12 @@ MavlinkFTP::_workList(PayloadHeader *payload, bool list_hidden)
 #endif
 			// For files we get the file size as well
 			direntType = kDirentFile;
-			snprintf(buf, sizeof(buf), "%s/%s", dirPath, result->d_name);
-			struct stat st;
+			if (snprintf(buf, sizeof(buf), "%s/%s", dirPath, result->d_name)) {
```
Comment (bkueng) [inline src/modules/mavlink/mavlink_ftp.cpp]: Shouldn't we compare against `sizeof(buf)`? See http://www.cplusplus.com/reference/cstdio/snprintf/

File: .gitmodules [hunk 3]
```diff
@@ -34,7 +34,7 @@
 	url = https://github.com/PX4/DriverFramework.git
 [submodule "src/lib/ecl"]
 	path = src/lib/ecl
-	url = https://github.com/PX4/ecl.git
+	url = https://github.com/lis-epfl/ecl.git
```
Comment (julianoes) [inline .gitmodules]: We can't merge this like that, the ecl PR needs to be merged first and then the reference of the ecl submodule needs to be changed

File: src/modules/mavlink/mavlink_ftp.cpp (hunk 2 above)
Comment (jlecoeur) [inline src/modules/mavlink/mavlink_ftp.cpp]: > Notice that only when this returned value is non-negative and less than n, the string has been completely written.

Fixed, thanks @bkueng

File: src/systemcmds/tests/test_matrix.cpp (hunk 1 above)
Comment (julianoes) [inline src/systemcmds/tests/test_matrix.cpp]: Odd.

File: .gitmodules (hunk 3 above)
Comment (jlecoeur) [inline .gitmodules]: Definitely

File: src/systemcmds/tests/test_matrix.cpp (hunk 1 above)
Comment (jlecoeur) [inline src/systemcmds/tests/test_matrix.cpp]: Ok I am confused because now it compiles with `ut_test(fabs(d(0, 0) - 1.0) < 1e-5);`, but not `ut_test(fabs(d(0, 0) - 1.0f) < 1e-5);`. So I must have made a mistake when uploading my code.

Either way this does not make sense to me, and it seems like an issue with the compiler trying to do optimizations that may reappear later.

**Comment by jlecoeur** [comment]
I marked this WIP because I do not have a fix for test_matrix.cpp, see some results with different targets/compilers:
 
| test_matrix.cpp:628   | posix / GCC7.1.1  | posix / clang4.0.0  | px4fmu-v5 / arm-none-eabi-gcc5.4.1  |
|---|---|---|---|
| **A**  | `test_matrix.cpp:640:1: internal compiler error: in trunc_int_for_mode, at explow.c:55`  |  OK |  OK  |
| **B**  | `test_matrix.cpp:640:1: internal compiler error: in trunc_int_for_mode, at explow.c:55`  | OK  |  OK |
| **C**  | OK   | OK | ```test_matrix.cpp:628:28: error: call of overloaded 'fabs(double)' is ambiguous```  |

Where
A: `ut_test(fabs(d(0, 0) - 1) < 1e-5);`
B: `ut_test(fabs(d(0, 0) - 1.0f) < 1e-5);` 
C: `ut_test(fabs(d(0, 0) - 1.0) < 1e-5);`

@julianoes solution A (i.e. what is on master) works with clang. Is it possible to make clang the default for posix targets? This way archlinux users would not run into this issue until a solution is found for GCC 7.

**Comment by dagar** [comment]
@jlecoeur isn't B + gcc 7 fix the right answer?

Would `1e-5f` make it happy?
``` C
ut_test(fabs(d(0, 0) - 1.0f) < 1e-5f);
```

**Comment by jlecoeur** [comment]
@dagar not happy, I edited my comment with what you proposed, plus one using `fasbf`. I think all solutions should work, they just differ in the number of implicit casts.

Do you have an idea how to approach the problem? I could file a gcc bug, but they require a small code example to reproduce the bug 👎

**Comment by dagar** [comment]
No, but I don't really have a clue what's actually going on with the underlying bug.
Any potential workarounds? Is FLT_EPSILON any different than the literal?
Any difference with ut_compare_float() or ut_less_than() instead?

**Comment by LorenzMeier** [comment]
I merged the ECL change - if you update the submodule you should be able to continue.

**Comment by jlecoeur** [comment]
Updated submodule and rebased to master

**Comment by jlecoeur** [comment]
For reference, here are more tests that add to the oddity:
- this works :
```c++
bool MatrixTest::vector2Tests()
{
	Vector2f a(1, 0);
	Matrix<float, 2, 1> d(a);
	ut_test(fabs(d(0, 0) - 1) < 1e-5);
        ut_test(fabs(d(1, 0) - 0) < 1e-5);
	return true;
}
```
- but this doesn't (variable `d` is reused):
```c++
bool MatrixTest::vector2Tests()
{
	Vector2f a(1, 0);
	Matrix<float, 2, 1> d(a);
	ut_test(fabs(d(0, 0) - 1) < 1e-5);
        ut_test(fabs(d(1, 0) - 0) < 1e-5);
	Vector2f e(d);
	ut_test(fabs(e(0) - 1) < 1e-5);
	return true;
}
```
- but then...*wait for it*... this works (modified value of `a`):
```c++
bool MatrixTest::vector2Tests()
{
	Vector2f a(1, 1);
	Matrix<float, 2, 1> d(a);
	ut_test(fabs(d(0, 0) - 1) < 1e-5);
        ut_test(fabs(d(1, 0) - 0) < 1e-5);
	Vector2f e(d);
	ut_test(fabs(e(0) - 1) < 1e-5);
	return true;
}
```

This really smells like GCC trying to optimize `d` away, but failing.

**Comment by jlecoeur** [comment]
@dagar I found a workaround by declaring `d` static. I added a comment to explain why it was done.

**Comment by dagar** [comment]
Odd, but I'm fine with it for this test.

**Comment by julianoes** [comment]
Thanks a lot @jlecoeur!

**Comment by jlecoeur** [comment]
Great! Thank you.
