### PR TITLE
Upgrade Eigen version

### PR DESCRIPTION
**Pull request by LorenzMeier**
@TSC21 This will fail build tests - how did you build successfully?

### CODE REVIEW

**Comment by TSC21** [comment]
Strange. Let me recheck.

**Comment by TSC21** [comment]
`make posix` on my machine gives a clean build. So I think this may be related to flag configs, probably on Travis side.

**Comment by TSC21** [comment]
Correction: Seems like I also get this error with `make posix` on my machine.

**Comment by TSC21** [comment]
We will have to find a way of activating this block of code: https://github.com/PX4/eigen/blob/3.2.5/Eigen/src/Core/MathFunctions.h#L789-L794. Is there a way of activating this flag on POSIX side?

**Comment by TSC21** [comment]
I'm leaving here an output with more verbosity so to help figure this out: http://pastebin.com/wfUWBZ4P. Probably there's a need to add a fix in the [POSIX toolchain config](https://github.com/PX4/Firmware/blob/master/makefiles/posix/toolchain_native.mk).

**Comment by LorenzMeier** [comment]
@TSC21 I actually doubt that your Eigen version ever built correctly. The target including the Eigen unit test is px4fmu-v2_test, which yields this error:
```
CMD:     tests
In file included from /Users/lorenzmeier/src/Firmware/Build/px4fmu-v2_test.build/nuttx-export/include/math.h:52:0,
                 from /Users/lorenzmeier/src/Firmware/Build/px4fmu-v2_test.build/nuttx-export/include/cxx/cmath:46,
                 from /Users/lorenzmeier/src/Firmware/src/systemcmds/tests/test_eigen.cpp:41:
/Users/lorenzmeier/src/Firmware/src/lib/eigen/Eigen/src/Core/MathFunctions.h: In function 'bool Eigen::numext::isfinite(const std::complex<_Tp>&)':
/Users/lorenzmeier/src/Firmware/Build/px4fmu-v2_test.build/nuttx-export/include/arch/math.h:166:11: error: expected unqualified-id before '(' token
           (__extension__ ({int __cy = fpclassify(__y); \
           ^
/Users/lorenzmeier/src/Firmware/src/lib/eigen/Eigen/src/Core/MathFunctions.h:824:18: note: in expansion of macro 'isfinite'
   return numext::isfinite(numext::real(x)) && numext::isfinite(numext::imag(x));
                  ^
compilation terminated due to -Wfatal-errors.
```

Could you explain what the added benefit is when upgrading from 3.2 to 3.2.5? What did it fix, and did you actually run the Eigen test on the hardware?

**Comment by LorenzMeier** [comment]
@TSC21 POSIX builds fine now, btw.

**Comment by TSC21** [comment]
@LorenzMeier well I was probably fooling myself on thinking that it was building the right version of the firmware. I was using git commands inside `src/lib/` so to update the eigen to the 3.2.5 version but then I realize that when I was issuing `make`, the git hash for the eigen submodule was being set to the 3.2 version, which means it was still compiling the older version.

Anyhow, what I did was removing the eigen folder and replace it with the 3.2.5 one and recompile, which gave me the error on POSIX. Probably it gives me the error building `px4fmu_v2` - have to try. So what's the best way of updating a submodule hash version in this case?

Relative to the workarounds: I tried to apply https://github.com/PX4/Firmware/commit/f57c42505bbb7107ec4bcd06b7fbb0d38d1acf2a also, but it wasn't enough. What was missing was https://github.com/PX4/Firmware/commit/246fd9538efbe0bc3c7167c4db86240a6787cc2a but I didn't know were to add it, so nice catch.

**Comment by TSC21** [comment]
I'll be playing around with https://github.com/PX4/Firmware/tree/eigen_upgrade, launch tests, and if everything comes to work OK, I'll let you know.

**Comment by LorenzMeier** [comment]
I did have a brief look. Most likely the NuttX infinite macro needs to be replaced with a function to make this work.

Again, what is the benefit of upgrading Eigen? What are you trying to solve?

**Comment by TSC21** [comment]
Mostly because of the compatibility with CUDA and usage of CUDA functions. Bringing up POSIX build into an Nvidia Jetson, for example, will also allows the usage of it's CUDA cores for processing. Having Eigen math being processed there is the first step.
Also it is just a way of keeping the PX4 submodules up to date with the current most updated state.

> Most likely the NuttX infinite macro needs to be replaced with a function to make this work.

Yes it's what I'm trying to check right now.

**Comment by vooon** [comment]
I don't think that such powerful CPU like jetson really require optimization of autopilot's math.

But other question to Lorenz, why not to use eigen provided by OS? As i see, eigen only used on linux targets (ros/posix), libeigen-dev solves all needs.
Or that because OSX?

**Comment by TSC21** [comment]
> I don't think that such powerful CPU like jetson really require optimization of autopilot's math.

That really depends on how you want to distribute the computing power of your apps. Jetson CPU is powerful but not that powerful.

**Comment by TSC21** [comment]
I extended the issue here: https://github.com/PX4/NuttX/issues/62

**Comment by LorenzMeier** [comment]
Because we can't trust the OS version and it wildly varies

**Comment by TSC21** [comment]
Ping @Zefz

**Comment by LorenzMeier** [comment]
@TSC21 Awesome! Really good work!
